- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      tags: always
      apt:
         update_cache: yes
      changed_when: False

# run roles
- hosts: all
  tags: base
  become: true
  - import_tasks: tasks/root/packages.yml

- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
