#!/bin/bash
# -*- shell-script -*-
TMP_DIR=$HOME/w/ansible/proj_mgmt

rm -rf $TMP_DIR/pkg
mkdir -p $TMP_DIR/pkg/ssh/{mclay,root}

echo "copy mclay's ssh files"
cp ~/.ssh/{authorized_keys,id_rsa,id_rsa.pub} $TMP_DIR/pkg/ssh/mclay

echo "copy root's ssh files"
scp root@localhost:.ssh/{authorized_keys,id_rsa,id_rsa.pub} $TMP_DIR/pkg/ssh/root > /dev/null

mkdir -p $TMP_DIR/pkg/bin
cp my_epoch my_seconds2time $TMP_DIR/pkg/bin


(cd $TMP_DIR; tar czf pkg.tar.gz pkg; rm -rf pkg)
