- name: .up repo
  become_user: mclay
  git:
    repo: git@bitbucket.com:rtmclay/rtm_up.git
    dest: .up
  sudo_user: mclay
    
- name: usefulTools repo
  become_user: mclay
  git:
    repo:  git@riverton.ddns.net:usefulTools
    dest:  w/usefulTools
  sudo_user: mclay
