- name: Configure click_to_focus
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/click_to_focus
    value_type: 'bool'
    value: 'false'
    
    
- name: Configure Numix theme
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/theme
    value_type: 'string'
    value: 'Numix'
    
- name: Set workspace count
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/workspace_count
    value_type: 'int'
    value: '5'


- name: Configure Remove icons from desktop
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /desktop-icons/style
    value_type: 'int'
    value: '0'
    
    
