- name: Configure click_to_focus
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/click_to_focus
    value_type: 'bool'
    value: 'false'
    
    
- name: Configure Numix theme
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/theme
    value_type: 'string'
    value: 'Numix'
    
- name: Set workspace count
  become_user: mclay
  xfconf:
    channel: xfwm4
    property: /general/workspace_count
    value_type: 'int'
    value: '5'


- name: Configure Remove icons from desktop
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /desktop-icons/style
    value_type: 'int'
    value: '0'

- name: Configure Remove icons from desktop
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/single-workspace-mode
    value_type: 'bool'
    value: 'false'
    
- name: disable lock screen
  become_user: mclay
  xfconf:
    channel: xfce4-screensaver
    property: /lock/enabled
    value_type: 'bool'
    value: 'false'

- name: set beach background screen0:workspace0
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual1/workspace0/last-image
    value_type: 'string'
    value: '/home/mclay/.up/backgrounds/Beach_by_Renato_Giordanelli.jpg'

- name: set Cairn background screen0:workspace1
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual1/workspace1/last-image
    value_type: 'string'
    value: '/home/mclay/.up/backgrounds/Cairn_by_Sylvain_Naudin.jpg'

- name: set Winter Mountains background screen0:workspace2
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual1/workspace2/last-image
    value_type: 'string'
    value: '/home/mclay/.up/backgrounds/Mountains_by_JamesPickles.jpg'
    
- name: set Icy Stones background screen0:workspace3
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual1/workspace3/last-image
    value_type: 'string'
    value: '/home/mclay/.up/backgrounds/Icystones2.jpg'
    
- name: set Power of Words background screen0:workspace4
  become_user: mclay
  xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual1/workspace4/last-image
    value_type: 'string'
    value: '/home/mclay/.up/backgrounds/Power_of_Words_by_Antonio_Litterio.jpg

- name: Ctrl-left -> Left workspace
  become_user: mclay
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary>Left
    value_type: 'string'
    value: "left-workspace-key"

- name: Ctrl-Right -> Right workspace
  become_user: mclay
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/<Primary>Right
    value_type: 'string'
    value: "right-workspace-key"



    
