- name: Install packages
  apt:
    name:
      - cmake
      - emacs
      - enscript
      - evince
      - expect
      - flex
      - g++
      - gawk
      - gdb
      - gfortran
      - htop
      - m4
      - make
      - meld
      - mysql-client
      - mysql-common
      - mysql-server
      - ncurses-base
      - ncurses-bin
      - ncurses-term
      - stow
      - tcl
      - tcl-dev
      - tcl-expect
      - tcsh
      - tmux
      - tree
      - zsh
      - zsh-common
